"""use unified enums for documents

Revision ID: aa503c802de3
Revises: ee0f1b78c49b
Create Date: 2025-10-14 10:38:04.810373

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa503c802de3'
down_revision: Union[str, Sequence[str], None] = 'ee0f1b78c49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('bewerbung', 'krankenkasse', 'urlaub_bescheinigung', 'attest', 'urlaubsantrag', 'fehlzeit', 'sonstige', name='documenttype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=sa.Enum('bewerbung', 'krankenkasse', 'urlaub_bescheinigung', 'attest', 'urlaubsantrag', 'fehlzeit', 'sonstige', name='documenttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
