"""add avatar_url to employees

Revision ID: ee0f1b78c49b
Revises: e81ea845b2af
Create Date: 2025-10-14 04:52:15.665210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0f1b78c49b'
down_revision: Union[str, Sequence[str], None] = 'e81ea845b2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.drop_index('idx_sl_employee_id', table_name='sick_leaves')
    op.drop_index('idx_vr_employee_id', table_name='vacation_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vr_employee_id', 'vacation_requests', ['employee_id'], unique=False)
    op.create_index('idx_sl_employee_id', 'sick_leaves', ['employee_id'], unique=False)
    op.drop_column('employees', 'avatar_url')
    # ### end Alembic commands ###
