# ui/Dockerfile.dev
FROM node:20-alpine
WORKDIR /app

RUN npm install -g corepack pnpm

# pnpm aktivieren
RUN corepack enable

# Lockfile & manifest zuerst kopieren -> sauberes layer caching
COPY pnpm-lock.yaml package.json ./

# deterministische Installation
RUN pnpm install --frozen-lockfile

# restlicher Code
COPY . .

EXPOSE 5173
CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]
